version: '2'
services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
          - ./:/var/www
        ports:
          - "8080:80"
        links:
          - php-fpm        
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
          - ./:/var/www
        links:
          - mysql  
        environment:
          - "DB_PORT=3306"
          - "DB_HOST=mysql"                          
    mysql:                         
        image: mysql:5.7
        volumes:
          - ./storage/docker/mysql:/var/lib/mysql            
        environment:               
          - "MYSQL_ROOT_PASSWORD=qwe"
          - "MYSQL_USER=qwe"
          - "MYSQL_PASSWORD=qwe"
          - "MYSQL_ROOT_PASSWORD=test_db"
        ports:                      
          - "33061:3306"